version: '3.9'
services:
  api:
    image: yasirq23/corner_api:part1
    command: python manage.py runserver 0.0.0.0:8000
    build: ./api
    env_file: .env
    volumes:
      - ./api/:/code
    ports:
      - 8000:8000