version: '3.9'

services:
  api:
    image: jonathan92/corner_api:part1
    build: ./api
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
volumes:
  postgres_data: